name: Lint
on: [ push ]

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install clj-kondo
        run: sudo .bin/install-clj-kondo

      - name: Lint src with clj-kondo
        run: clj-kondo --lint src